// Import the compiled contract ABI (Application Binary Interface)
// This file is usually generated by the Solidity compiler or Hardhat after contract compilation in the form of a file called CrowdFunding.json in a artifacts/contracts/CrowdFunding.sol folder which will need to my moved into the Context folder 
import crowdFunding from "./CrowdFunding.json";                                                // from tutorial 


// Blockchain Configuration
// The Ethereum address where your smart contract is deployed.
// IMPORTANT: This should be updated to match the live address once deployed.
export const CrowdFundingAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";               // from tutorial refine with my address 
// The ABI defines the contract's interface — functions, events, types, etc.
// It enables your frontend to understand how to interact with the smart contract.
export const CrowdFundingABI = crowdFunding.abi;                                               // from tutorial 