/**
 * Constants Configuration for Smart Contract Interaction
 *
 * Based on: Daulat Hussain’s Web3.0 Crowdfunding Tutorial
 * https://www.youtube.com/watch?v=AcXVKkYnu1c
 *
 * Modifications by Sahar Choudhury:
 * - Updated the contract address to reflect the deployed contract on Hardhat (0x5FbD...aa3)
 */


// Import the compiled contract ABI (Application Binary Interface)
// This file is usually generated by the Solidity compiler or Hardhat after contract compilation in the form of a file called CrowdFunding.json in a artifacts/contracts/CrowdFunding.sol folder which will need to my moved into the Context folder 
import crowdFunding from "./CrowdFunding.json";                                                


// Blockchain Configuration
// The Ethereum address where your smart contract is deployed.
// IMPORTANT: This should be updated to match the live address once deployed.
export const CrowdFundingAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";              
// The ABI defines the contract's interface — functions, events, types, etc.
// It enables your frontend to understand how to interact with the smart contract.
export const CrowdFundingABI = crowdFunding.abi;                                             